services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: selections
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u root -p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:    
      - ./mysql:/var/lib/mysql
    networks:
      - go-network
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
       # - " 6381:6381/udp"
      - "4318:4318" # localhost tracing
      - "14268:14268"
      - "16686:16686" #UI interface
    networks:
      - go-network
  web-app: 
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - go-network
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root
      DB_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
      JAEGER_AGENT_HOST: jaeger
      JAEGER_AGENT_PORT: 4318

volumes:
  mysql:
networks:
  go-network:
